# Generated by Django 3.1.1 on 2020-09-16 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('recipe', models.CharField(max_length=500, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('calorie', models.FloatField(null=True)),
                ('carbohydrate', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('Lipid', models.FloatField(null=True)),
                ('salt', models.FloatField(null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('Dietary_Fiber', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('Vitaminc', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=5)),
                ('age', models.IntegerField()),
                ('Repmaterial', models.CharField(max_length=100)),
                ('pretag', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
