# Generated by Django 3.1.1 on 2020-09-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_myrefrigerator'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', models.IntegerField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('material', models.CharField(max_length=200, null=True)),
                ('recipe', models.CharField(max_length=500, null=True)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('calorie', models.FloatField(null=True)),
                ('carbohydrate', models.FloatField(null=True)),
                ('protein', models.FloatField(null=True)),
                ('Lipid', models.FloatField(null=True)),
                ('salt', models.FloatField(null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('Dietary_Fiber', models.FloatField(null=True)),
                ('calcium', models.FloatField(null=True)),
                ('Vitaminc', models.FloatField(null=True)),
                ('sugars', models.FloatField(null=True)),
            ],
        ),
    ]
